fix: show step one not two times
delta10/signalen-frontend-wcag pull request #316
Opened 2024-12-18 14:34 UTC by justiandevs

Fixes #303

2024-12-19 09:08 UTC, justiandevs commented
@Robbert zou jij dit kunnen testen, of dit het probleem oplost?

2024-12-23 10:39 UTC, Yolijn commented
Ik heb dit zojuist getest met de preview branch. Helaas krijg ik op Safari in private mode als ik snel iets invul en submit op stap 1 nog steeds opnieuw de vraag én is hij leeg gemaakt. Deze PR lost het probleem dus niet op.

2024-12-23 10:40 UTC, Yolijn requested changes
Ik heb dit zojuist getest met de preview branch. Helaas krijg ik op Safari in private mode als ik snel iets invul en submit op stap 1 nog steeds opnieuw de vraag én is hij leeg gemaakt. Deze PR lost het probleem dus niet op.

2024-12-23 13:09 UTC, iehkaatee commented
> Ik heb dit zojuist getest met de preview branch. Helaas krijg ik op Safari in private mode als ik snel iets invul en submit op stap 1 nog steeds opnieuw de vraag én is hij leeg gemaakt. Deze PR lost het probleem dus niet op.

Ik probeer dit zelf op de manier zoals je hierboven heb beschreven te reproduceren maar lijkt bij mij niet meer op te treden. Ik heb net iets meer dan 5 minuten opnieuw een incognito window geopent en zowel lokaal als via de preview url het geprobeerd. 

Heb je nog een bepaalde query waar die je invult als melding?

2024-12-24 12:37 UTC, iehkaatee commented
Besproken: Dit lijkt niet de fix voor het probleem te zijn want het lijkt alsnog op te treden. @bartjkdp had het idee dat misschien zou kunnen komen door vercel's preview mode en extra functionaliteit die daarbij gerendered wordt. 

Laten we in de gaten houden hoe vaak dit optreedt.

2024-12-27 16:16 UTC, Yolijn commented
Ik heb het niet meer gezien tijdens het testen vandaag. Ik heb het idee dat het ook zou kunnen dat de `useEffect` dependencies die niet allemaal waren meegegeven ook hier het probleem konden zijn. Die zijn inmiddels op de meeste plekken aangevuld, dus wellicht is dit issue als side-effect opgelost

2024-12-30 08:09 UTC, iehkaatee commented
Laten we dan de PR sluiten en in de gaten houden of het nog optreedt.

2024-12-30 08:09 UTC, closed without merging

2024-12-31 11:13 UTC, bartjkdp commented
Ik kan het ook niet meer reproduceren.